export type ComponentCatalogItem = {
  slug: string;
  name: string;
  layer: "primitive" | "radix" | "composite" | "block-helper" | "ornament";
  status: "built" | "basis" | "planned";
  file: string;
  notes: string;
  snippet: string;
  dependencies?: string[];
  accessibility?: string;
};
export const componentCatalog: ComponentCatalogItem[] = [
  { slug: 'accordion', name: 'Accordion', layer: 'primitive', status: 'built', file: 'src/components/ui/accordion.tsx', notes: 'Accordion source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Accordion />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'alert-dialog', name: 'Alert Dialog', layer: 'radix', status: 'built', file: 'src/components/ui/alert-dialog.tsx', notes: 'Alert Dialog source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<AlertDialog />', dependencies: ['@radix-ui/react-alert-dialog'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'alert', name: 'Alert', layer: 'primitive', status: 'built', file: 'src/components/ui/alert.tsx', notes: 'Alert source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Alert />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'aspect-ratio', name: 'Aspect Ratio', layer: 'primitive', status: 'built', file: 'src/components/ui/aspect-ratio.tsx', notes: 'Aspect Ratio source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<AspectRatio />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'avatar-group', name: 'Avatar Group', layer: 'composite', status: 'built', file: 'src/components/ui/avatar-group.tsx', notes: 'Avatar Group source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<AvatarGroup />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'avatar', name: 'Avatar', layer: 'radix', status: 'built', file: 'src/components/ui/avatar.tsx', notes: 'Avatar source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Avatar />', dependencies: ['@radix-ui/react-avatar'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'badge', name: 'Badge', layer: 'primitive', status: 'built', file: 'src/components/ui/badge.tsx', notes: 'Badge source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Badge />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'banner', name: 'Banner', layer: 'primitive', status: 'built', file: 'src/components/ui/banner.tsx', notes: 'Banner source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Banner />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'breadcrumb', name: 'Breadcrumb', layer: 'primitive', status: 'built', file: 'src/components/ui/breadcrumb.tsx', notes: 'Breadcrumb source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Breadcrumb />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'button-group', name: 'Button Group', layer: 'primitive', status: 'built', file: 'src/components/ui/button-group.tsx', notes: 'Button Group source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<ButtonGroup />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'button', name: 'Button', layer: 'primitive', status: 'built', file: 'src/components/ui/button.tsx', notes: 'Tone, shape, size, tilt, loading-ready press behavior, and universal focus ring.', snippet: '<Button tone="pink" tilt="left">Do the thing</Button>', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'calendar', name: 'Calendar', layer: 'composite', status: 'basis', file: 'src/components/ui/calendar.tsx', notes: 'Calendar basis for single-date and date-picker composition.', snippet: '<Calendar />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'callout', name: 'Callout', layer: 'block-helper', status: 'built', file: 'src/components/ui/callout.tsx', notes: 'Callout source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Callout />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'card', name: 'Card', layer: 'primitive', status: 'built', file: 'src/components/ui/card.tsx', notes: 'Composition shell with tone, radius, tilt, and pressure axes.', snippet: '<Card tone="acid" radius="none"><CardHeader><CardTitle>Receipt</CardTitle></CardHeader></Card>', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'carousel', name: 'Carousel', layer: 'composite', status: 'basis', file: 'src/components/ui/carousel.tsx', notes: 'Carousel source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Carousel />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'chart', name: 'Chart', layer: 'composite', status: 'basis', file: 'src/components/ui/chart.tsx', notes: 'Chart source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Chart />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'checkbox', name: 'Checkbox', layer: 'primitive', status: 'built', file: 'src/components/ui/checkbox.tsx', notes: 'Checkbox source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Checkbox />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'code-block', name: 'Code Block', layer: 'block-helper', status: 'built', file: 'src/components/ui/code-block.tsx', notes: 'Code Block source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<CodeBlock />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'code-tabs', name: 'Code Tabs', layer: 'block-helper', status: 'built', file: 'src/components/ui/code-tabs.tsx', notes: 'Code Tabs source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<CodeTabs />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'combobox', name: 'Combobox', layer: 'composite', status: 'built', file: 'src/components/ui/combobox.tsx', notes: 'Combobox source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Combobox />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'command', name: 'Command', layer: 'composite', status: 'built', file: 'src/components/ui/command.tsx', notes: 'Command source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Command />', dependencies: ['cmdk'], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'context-menu', name: 'Context Menu', layer: 'radix', status: 'built', file: 'src/components/ui/context-menu.tsx', notes: 'Context Menu source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<ContextMenu />', dependencies: ['@radix-ui/react-context-menu'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'copy-button', name: 'Copy Button', layer: 'block-helper', status: 'built', file: 'src/components/ui/copy-button.tsx', notes: 'Copy Button source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<CopyButton />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'data-table', name: 'Data Table', layer: 'composite', status: 'built', file: 'src/components/ui/data-table.tsx', notes: 'Sortable/filterable/paginated table basis with row selection and empty/loading states.', snippet: '<DataTable columns={columns} data={rows} enableSearch selectable />', dependencies: [], accessibility: 'Table semantics, keyboard-reachable controls, row-selection labels, empty/loading states.' },
  { slug: 'date-picker', name: 'Date Picker', layer: 'composite', status: 'basis', file: 'src/components/ui/date-picker.tsx', notes: 'Popover calendar composition for form surfaces.', snippet: '<DatePicker />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'dialog', name: 'Dialog', layer: 'radix', status: 'built', file: 'src/components/ui/dialog.tsx', notes: 'Radix Dialog behavior with feral overlay styling and focus receipts.', snippet: '<Dialog><DialogTrigger asChild><Button>Open</Button></DialogTrigger><DialogContent /></Dialog>', dependencies: ['@radix-ui/react-dialog'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'dropdown-menu', name: 'Dropdown Menu', layer: 'radix', status: 'built', file: 'src/components/ui/dropdown-menu.tsx', notes: 'Dropdown Menu source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<DropdownMenu />', dependencies: ['@radix-ui/react-dropdown-menu'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'empty-state', name: 'Empty State', layer: 'primitive', status: 'built', file: 'src/components/ui/empty-state.tsx', notes: 'Empty State source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<EmptyState />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'field', name: 'Field', layer: 'primitive', status: 'built', file: 'src/components/ui/field.tsx', notes: 'Field source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Field />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'file-upload', name: 'File Upload', layer: 'composite', status: 'built', file: 'src/components/ui/file-upload.tsx', notes: 'File Upload source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<FileUpload />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'form', name: 'Form', layer: 'composite', status: 'built', file: 'src/components/ui/form.tsx', notes: 'Form source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Form />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'hover-card', name: 'Hover Card', layer: 'radix', status: 'built', file: 'src/components/ui/hover-card.tsx', notes: 'Hover Card source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<HoverCard />', dependencies: ['@radix-ui/react-hover-card'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'image-card', name: 'Image Card', layer: 'composite', status: 'built', file: 'src/components/ui/image-card.tsx', notes: 'Image Card source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<ImageCard />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'input-group', name: 'Input Group', layer: 'composite', status: 'built', file: 'src/components/ui/input-group.tsx', notes: 'Input Group source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<InputGroup />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'kbd', name: 'Kbd', layer: 'block-helper', status: 'built', file: 'src/components/ui/kbd.tsx', notes: 'Kbd source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Kbd />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'marquee', name: 'Marquee', layer: 'primitive', status: 'built', file: 'src/components/ui/marquee.tsx', notes: 'Marquee source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Marquee />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'menubar', name: 'Menubar', layer: 'radix', status: 'built', file: 'src/components/ui/menubar.tsx', notes: 'Menubar source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Menubar />', dependencies: ['@radix-ui/react-menubar'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'meter', name: 'Meter', layer: 'primitive', status: 'built', file: 'src/components/ui/meter.tsx', notes: 'Meter source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Meter />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'navigation-menu', name: 'Navigation Menu', layer: 'radix', status: 'built', file: 'src/components/ui/navigation-menu.tsx', notes: 'Navigation Menu source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<NavigationMenu />', dependencies: ['@radix-ui/react-navigation-menu'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'ornaments', name: 'Ornaments', layer: 'ornament', status: 'built', file: 'src/components/ui/ornaments.tsx', notes: 'Feral-specific visual moat: bursts, arrows, stamps, splats, stickers, labels, and warning trash.', snippet: '<Ornaments />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'otp-input', name: 'OTP Input', layer: 'composite', status: 'built', file: 'src/components/ui/otp-input.tsx', notes: 'OTP Input source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<OTPInput />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'pagination', name: 'Pagination', layer: 'composite', status: 'built', file: 'src/components/ui/pagination.tsx', notes: 'Pagination source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Pagination />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'popover', name: 'Popover', layer: 'radix', status: 'built', file: 'src/components/ui/popover.tsx', notes: 'Popover source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Popover />', dependencies: ['@radix-ui/react-popover'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'preview-frame', name: 'Preview Frame', layer: 'block-helper', status: 'built', file: 'src/components/ui/preview-frame.tsx', notes: 'Preview Frame source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<PreviewFrame />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'progress', name: 'Progress', layer: 'radix', status: 'built', file: 'src/components/ui/progress.tsx', notes: 'Progress source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Progress />', dependencies: ['@radix-ui/react-progress'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'radio', name: 'Radio', layer: 'primitive', status: 'built', file: 'src/components/ui/radio.tsx', notes: 'Radio source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Radio />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'resizable', name: 'Resizable', layer: 'composite', status: 'basis', file: 'src/components/ui/resizable.tsx', notes: 'Resizable source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Resizable />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'scroll-area', name: 'Scroll Area', layer: 'radix', status: 'built', file: 'src/components/ui/scroll-area.tsx', notes: 'Scroll Area source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<ScrollArea />', dependencies: ['@radix-ui/react-scroll-area'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'separator', name: 'Separator', layer: 'radix', status: 'built', file: 'src/components/ui/separator.tsx', notes: 'Separator source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Separator />', dependencies: ['@radix-ui/react-separator'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'sheet', name: 'Sheet', layer: 'radix', status: 'built', file: 'src/components/ui/sheet.tsx', notes: 'Sheet source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Sheet />', dependencies: ['@radix-ui/react-dialog'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'sidebar', name: 'Sidebar', layer: 'composite', status: 'built', file: 'src/components/ui/sidebar.tsx', notes: 'Sidebar source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Sidebar />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'skeleton', name: 'Skeleton', layer: 'primitive', status: 'built', file: 'src/components/ui/skeleton.tsx', notes: 'Skeleton source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Skeleton />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'slider', name: 'Slider', layer: 'radix', status: 'built', file: 'src/components/ui/slider.tsx', notes: 'Slider source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Slider />', dependencies: ['@radix-ui/react-slider'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'sonner', name: 'Toast', layer: 'composite', status: 'basis', file: 'src/components/ui/sonner.tsx', notes: 'Toast provider/hook basis; tiny interface pigeons that arrive, yell, and leave.', snippet: '<Toast />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'spinner', name: 'Spinner', layer: 'primitive', status: 'built', file: 'src/components/ui/spinner.tsx', notes: 'Spinner source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Spinner />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'stat-card', name: 'Stat Card', layer: 'composite', status: 'built', file: 'src/components/ui/stat-card.tsx', notes: 'Stat Card source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<StatCard />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'stepper', name: 'Stepper', layer: 'composite', status: 'built', file: 'src/components/ui/stepper.tsx', notes: 'Stepper source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Stepper />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'switch', name: 'Switch', layer: 'primitive', status: 'built', file: 'src/components/ui/switch.tsx', notes: 'Switch source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Switch />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'table', name: 'Table', layer: 'primitive', status: 'built', file: 'src/components/ui/table.tsx', notes: 'Table source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Table />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'tabs', name: 'Tabs', layer: 'composite', status: 'built', file: 'src/components/ui/tabs.tsx', notes: 'Tabs source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Tabs />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'theme-selector', name: 'Theme Selector', layer: 'composite', status: 'built', file: 'src/components/ui/theme-selector.tsx', notes: 'Theme Selector source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<ThemeSelector />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'timeline', name: 'Timeline', layer: 'composite', status: 'built', file: 'src/components/ui/timeline.tsx', notes: 'Timeline source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Timeline />', dependencies: [], accessibility: 'Native semantic base; focus-visible styles; visual variance stays separate from meaning.' },
  { slug: 'toggle-group', name: 'Toggle Group', layer: 'radix', status: 'built', file: 'src/components/ui/toggle-group.tsx', notes: 'Toggle Group source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<ToggleGroup />', dependencies: ['@radix-ui/react-toggle-group'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'toggle', name: 'Toggle', layer: 'radix', status: 'built', file: 'src/components/ui/toggle.tsx', notes: 'Toggle source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Toggle />', dependencies: ['@radix-ui/react-toggle'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
  { slug: 'tooltip', name: 'Tooltip', layer: 'radix', status: 'built', file: 'src/components/ui/tooltip.tsx', notes: 'Tooltip source item generated from local UI inventory. Page must show preview, code, dependencies, and receipts.', snippet: '<Tooltip />', dependencies: ['@radix-ui/react-tooltip'], accessibility: 'Radix primitive owns keyboard/focus behavior; feral classes only style the costume.' },
];

export const componentGroups = Array.from(new Set(componentCatalog.map((item) => item.layer)));
export function getComponentBySlug(slug: string) { return componentCatalog.find((item) => item.slug === slug); }
